# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_a1:
    has_velocity_limits: true
#    max_velocity: 1.832596
    max_velocity: 0.9250245035569947
    has_acceleration_limits: true
    max_acceleration: 3.0
    has_deceleration_limits: true
    max_deceleration: -3.0
  joint_a2:
    has_velocity_limits: true
#    max_velocity: 1.640609
    max_velocity: 0.9232791743050003
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_deceleration_limits: true
    max_deceleration: -5.0
  joint_a3:
    has_velocity_limits: true
#    max_velocity: 1.745329
    max_velocity: 0.9389871375729493
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_deceleration_limits: true
    max_deceleration: -5.0
  joint_a4:
    has_velocity_limits: true
#    max_velocity: 2.373648
    max_velocity: 1.047197551196598
    has_acceleration_limits: true
    max_acceleration: 3.0
    has_deceleration_limits: true
    max_deceleration: -5.0
  joint_a5:
    has_velocity_limits: true
#    max_velocity: 2.251475
    max_velocity: 1.047197551196598
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_deceleration_limits: true
    max_deceleration: -5.0
  joint_a6:
    has_velocity_limits: true
#    max_velocity: 3.595378
    max_velocity: 1.396263401595464
    has_acceleration_limits: true
    max_acceleration: 7.0
    has_deceleration_limits: true
    max_deceleration: -7.0
