name: Rolling Source Build
on:
  workflow_dispatch:
    branches:
      - rolling
  push:
    branches:
      - rolling
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 3 * * *'

jobs:
  source:
    uses: ./.github/workflows/reusable-ros-tooling-source-build.yml
    with:
      ros_distro: rolling
      ref: rolling
      ros2_repo_branch: rolling
